image: ubuntu:18.04

before_script:
  - apt-get update -qq && apt-get install -y -qq \
    git-core gcc make autoconf automake libtool \
    git-core gcc g++ make autoconf autoconf-archive \
    automake libtool pkg-config libglib2.0-dev libglibmm-2.4-dev libzip-dev \
    libusb-1.0-0-dev libftdi1-dev check doxygen python-numpy \
    python-dev python-gi-dev python-setuptools swig default-jdk \
    git-core gcc make autoconf automake libtool pkg-config libglib2.0-dev python3-dev \
    git-core gcc make autoconf automake libtool pkg-config libglib2.0-dev \
    git-core g++ make cmake libtool pkg-config \
    libglib2.0-dev libboost-test-dev libboost-serialization-dev \ 
    libboost-filesystem-dev libboost-system-dev libqt5svg5-dev qtbase5-dev

build:
  script:
  - git clone git://sigrok.org/sigrok-util
  - cd sigrok-util/cross-compile/linux
  - ./sigrok-cross-linux
