image: ubuntu:18.04

before_script:
  - apt-get update && apt-get install -y \
    git gcc make autoconf automake libtool \
    g++ autoconf-archive \
    pkg-config libglib2.0-dev libglibmm-2.4-dev libzip-dev \
    libusb-1.0-0-dev libftdi1-dev check doxygen python-numpy \
    python-dev python-gi-dev python-setuptools swig default-jdk \
    libglib2.0-dev python3-dev cmake \
    libboost-test-dev libboost-serialization-dev \
    libboost-filesystem-dev libboost-system-dev libqt5svg5-dev qtbase5-dev

build:
  script:
  - git clone git://sigrok.org/sigrok-util
  - cd sigrok-util/cross-compile/linux
  - ./sigrok-cross-linux
