language: cpp

os: osx

matrix:
  include:
    - osx_image: xcode10  # OS X 10.13
    - osx_image: xcode9.3 # OS X 10.13
    - osx_image: xcode9.2 # OS X 10.12
    - osx_image: xcode8   # OS X 10.11

before_install:
  - brew update
  - brew bundle --force || true # Ignore failure
  # Pin glib to version 2.56.1
  - brew uninstall --ignore-dependencies glib
  - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/1862782b846b3eb85d2dfe59b43345b2d703cd8f/Formula/glib.rb

env:
  global:
    - PATH=/usr/local/opt/qt@5.5/bin:$PATH
    - LDFLAGS="-L/usr/local/opt/qt@5.5/lib"
    - CPPFLAGS="-I/usr/local/opt/qt@5.5/include"
    - PKG_CONFIG_PATH="/usr/local/opt/qt@5.5/lib/pkgconfig"

script:
  - git clone git://sigrok.org/sigrok-util
  - cd sigrok-util/cross-compile/macosx
  - ./sigrok-native-macosx

after_failure:
  - cat build/libsigrok/build/test-suite.log
